{% set name = "fireworks-ai" %}
{% set version = "0.15.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fireworks_ai-{{ version }}.tar.gz
  sha256: 03f0cc16f1ce2c22103d06c737954154fc7a138b2122c3b243d3ff2d65ede65e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - gitignore-parser
    - httpx-ws
    - openapi-spec-validator
    - prance
    - pytorch
    - tabulate
    - tqdm
    - python >=3.7
    - httpx
    - httpx-sse
    - pydantic
    - pillow

test:
  imports:
    - fireworks
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  home: https://fireworks.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
