{% set name = "fireworks-ai" %}
{% set version = "0.15.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fireworks_ai-{{ version }}.tar.gz
  sha256: 2380a53d92244c608fd398f8d97b97380d899f3ff710091f4b50917b75119ec2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - gitignore-parser
    - httpx-ws
    - openapi-spec-validator
    - prance
    - pytorch
    - tabulate
    - tqdm
    - python >={{ python_min }}
    - httpx
    - httpx-sse
    - pydantic
    - pillow

test:
  imports:
    - fireworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  home: https://fireworks.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
