{% set name = "fireworks-ai" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fireworks_ai-{{ version }}.tar.gz
  sha256: 414c6a791257eecd6dc571eb33a86e53dcc3768322aef82a5ac3151b1c2a209f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - python >=3.7
    - httpx
    - httpx-sse
    - pydantic
    - pillow

test:
  imports:
    - fireworks
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  home: https://fireworks.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
