{% set name = "fireworks-ai" %}
{% set version = "0.15.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fireworks_ai-{{ version }}.tar.gz
  sha256: b291f9808ae1203b020573f57fcbe4fdb0b60ff920be134a7e97d7b038238d76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - gitignore-parser
    - httpx-ws
    - openapi-spec-validator
    - prance
    - pytorch
    - tabulate
    - tqdm
    - python >={{ python_min }}
    - httpx
    - httpx-sse
    - pydantic
    - pillow

test:
  imports:
    - fireworks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  home: https://fireworks.ai
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
