schema_version: 1

context:
  name: fireworks-ai
  version: "1.2.21"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/5f/21/754ec540de0546f516a418d0ce73303f3edc3a0cc70efd41208732f61247/fireworks_ai-${{ version }}.tar.gz
  sha256: 93dd813377f5a1cba58cd1f711162dd2c12db9a2c31bd96121d48f67e8196b9a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing_extensions >=4.14,<5
    - aiohttp
    - sniffio
    - distro >=1.7.0,<2
    - httpx-aiohttp >=0.1.9
    - anyio >=3.5.0,<5
tests:
  - python:
      imports:
        - fireworks
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  license: MIT
  license_file: LICENSE
  homepage: https://fireworks.ai

extra:
  recipe-maintainers:
    - jan-janssen
