schema_version: 1

context:
  name: fireworks-ai
  version: "1.2.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/0f/12/46a3fafb4fdcfc973ca3cb5d65bcf6e1a1285abe3054b389e90108ae6678/fireworks_ai-${{ version }}.tar.gz
  sha256: 9441aa2fecf47da7b6fccb4b89b76f0a93ae4deacb51d7eb02cd21f91a8d61dc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<2.13
    - typing_extensions >=4.14,<5
    - aiohttp
    - sniffio
    - distro >=1.7.0,<2
    - httpx-aiohttp >=0.1.9
    - anyio >=3.5.0,<5
tests:
  - python:
      imports:
        - fireworks
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  license: MIT
  license_file: LICENSE
  homepage: https://fireworks.ai

extra:
  recipe-maintainers:
    - jan-janssen
