schema_version: 1

context:
  name: fireworks-ai
  version: "1.2.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fireworks_ai-${{ version }}.tar.gz
  sha256: dcf40ad63aaebcf85c5924785b086e69dcca385a338b7e14b15bfaa7c38d47cb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<2.13
    - typing_extensions >=4.14,<5
    - aiohttp
    - sniffio
    - distro >=1.7.0,<2
    - httpx-aiohttp >=0.1.9
    - anyio >=3.5.0,<5
tests:
  - python:
      imports:
        - fireworks
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Python client library for the Fireworks.ai Generative AI Platform
  license: MIT
  license_file: LICENSE
  homepage: https://fireworks.ai

extra:
  recipe-maintainers:
    - jan-janssen
